site_name: BigDL Doc Website
pages:
   - Home: index.md 
   - BigDL Docs: 
     - Overview: overview.md
     - Building: building.md
     - Getting Started: gettingstarted.md
     - Python Support: pythonsupport.md
     - Tutorials: tutorials.md
     - Visualization with TensorBoard: visualizationwithtensorboard.md
     - Running on EC2: runningonEC2.md 
     - Examples: examples.md
     - Programming Guide: ProgrammingGuide.md
     - Known Issues: knownissues.md  
   - About: About.md
theme: readthedocs
