site_name: BigDL Doc Website
theme: material
#theme: readthedocs
repo_name: 'GitHub'
repo_url: 'https://github.com/intel-analytics/BigDL'
edit_uri: 'docs/source/docs'

pages:
- Home: index.md 
- Release: release.md
- User Guide:
  - Build: build.md
  - Getting Started: getting-started.md
  - Turtorial: tutorials.md
  - Visualization With Tensorboard: visualization-with-tensorboard.md
  - Running on EC2: running-on-EC2.md
- Developer Guide: 
  - Examples: examples.md
  - Programming Guide: programming-guide.md
  - Python Support: python-support.md
- API Docs:
  - Scala Docs: javadoc.md
  - Python API Docs: python-api-doc.md
- Known Issues: known-issues.md
- Powered by: powered-by.md
- Support: support.md

extra:
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'


